version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: narcisse
      MONGO_INITDB_ROOT_PASSWORD: adminadmin
      MONGO_INITDB_DATABASE: database_de_narcisse
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  web:
    build: ../web
    container_name: flask_docker
    ports:
      - "5066:5066"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://narcisse:adminadmin@mongodb:27017/
    networks:
      - app-network
    depends_on:
      - mongodb

  web2:
    build: ../web2
    container_name: flask_docker_nodb
    ports:
      - "5067:5067"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - web
      - web2

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge