version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: narcisse
      MONGO_INITDB_ROOT_PASSWORD: adminadmin
      MONGO_INITDB_DATABASE: database_de_narcisse
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  web:
    build: ../
    container_name: flask_docker
    ports:
      - "5066:5066"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://narcisse:adminadmin@mongodb:27017/
    networks:
      - app-network
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge