version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: narcisse
      MONGO_INITDB_ROOT_PASSWORD: adminadmin
      MONGO_INITDB_DATABASE: database_de_narcisse
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: