apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
  clusterIP: None
  selector:
    app: mongodb
