apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.webdb.port }}
  type: ClusterIP