apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: narcisseuuh/webnodb:latest
        rollingUpdate:
          enabled: true
          maxSurge: "100%"
          maxUnavailable: "50%"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: {{ .Values.mongodb.port }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%