apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.webnodb.port }}
  type: ClusterIP